on: [push]

jobs:
  build:
    strategy: 
      matrix:
        board: [ambassador, asuka, asurada, atlas, auron-paine, auron-yuna, banjo, banon, bob, brask, brya, buddy, buddy-cfm, butterfly, candy, caroline, cave, celes, chell, cherry, clapper, constitution, coral, corsola, cyan, daisy, daisy-skate, daisy-spring, dedede, drallion, edgar, elm, endeavour, enguarde, eve, excelsior, expresso, falco, falco-li, fizz, fizz-cfm, gandof, glimmer, gnawty, grunt, guado, guado-cfm, guybrush, hana, hatch, heli, jacuzzi, kalista, kalista-cfm, kefka, kevin, kip, kukui, lars, leon, link, lulu, lumpy, mccloud, monroe, nami, nautilus, ninja, nissa, nocturne, nyan-big, nyan-blaze, nyan-kitty, octopus, orco, panther, parrot, parrot-ivb, peach-pi, peach-pit, peppy, puff, pyro, quawks, rammus, reef, reks, relm, reven, rex, rikku, rikku-cfm, samus, sand, sarien, scarlet, sentry, setzer, skyrim, snappy, soraka, squawks, staryu, stout, strongbad, stumpy, sumo, swanky, terra, tidus, tricky, trogdor, ultima, veyron-fievel, veyron-jaq, veyron-jerry, veyron-mickey, veyron-mighty, veyron-minnie, veyron-speedy, veyron-tiger, volteer, winky, wizpig, wolf, x86-alex, x86-alex-he, x86-mario, x86-zgb, x86-zgb-he, zako, zork]

    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 32768
          swap-size-mb: 64
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: download repo
        uses: actions/checkout@v4
      
      - name: run build
        run: |
          set -x
          sudo apt-get update
          sudo apt-get install -y pv

          sudo QUIET=1 ./build_complete.sh "${{ matrix.board }}"

      - name: upload img
        uses: actions/upload-artifact@v4
        with:
          name: badrecovery_${{ matrix.board }}.bin
          path: data/badrecovery_${{ matrix.board }}.bin
          compression-level: 7